# Render Blueprint
# https://render.com/docs/blueprint-spec

services:
  - type: web
    name: ags-break-tracker
    env: docker
    dockerfilePath: ./Dockerfile.railway
    plan: free
    region: oregon
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: AGS Break Tracker
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_TIMEZONE
        value: UTC
      - key: APP_URL
        value: https://ags-break-tracker-hmcu.onrender.com
      - key: APP_KEY
        value: base64:WAx9Aby1mD+XHK951ikF1NtmLMs5u6PQiVzOD4aiaA0=
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: notice
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: ags-break-tracker-db
          property: host
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        fromDatabase:
          name: ags-break-tracker-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: ags-break-tracker-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ags-break-tracker-db
          property: password
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: "120"
      - key: SESSION_SECURE_COOKIE
        value: "0"
      - key: CACHE_STORE
        value: database
      - key: BROADCAST_CONNECTION
        value: log
      - key: QUEUE_CONNECTION
        value: database
      - key: FILESYSTEM_DISK
        value: local
      - key: REDIS_CLIENT
        value: predis
      - key: MAIL_MAILER
        value: log

databases:
  - name: ags-break-tracker-db
    plan: free
    region: oregon
    databaseName: ags_break_tracker
