<?php

namespace Container3EHv3e3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGodModeCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\GodModeCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\GodModeCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:god-mode', [], 'Login as any user in the AGS Break Tracker Laravel app', false, #[\Closure(name: 'App\\Command\\GodModeCommand')] fn (): \App\Command\GodModeCommand => ($container->privates['App\\Command\\GodModeCommand'] ?? $container->load('getGodModeCommandService')));
    }
}
