<?php

namespace Container3EHv3e3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGodModeCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\GodModeCommand' shared autowired service.
     *
     * @return \App\Command\GodModeCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/GodModeCommand.php';

        $container->privates['App\\Command\\GodModeCommand'] = $instance = new \App\Command\GodModeCommand();

        $instance->setName('app:god-mode');
        $instance->setDescription('Login as any user in the AGS Break Tracker Laravel app');

        return $instance;
    }
}
