<?php

namespace App\Http\Controllers;

use App\Services\ElevenLabsService;
use App\Services\SlackService;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Cache;

class AlertController extends Controller
{
    public function __construct(
        protected ElevenLabsService $elevenLabs,
        protected SlackService $slack
    ) {}

    public function overbreakAlert(Request $request): Response
    {
        if (!$this->elevenLabs->isConfigured()) {
            return response('Voice alerts not configured', 503);
        }

        // Support both GET and POST
        $agentName = $request->input('agent_name') ?? $request->query('agent_name');
        $overMinutes = $request->input('over_minutes') ?? $request->query('over_minutes');

        if (!$agentName || !$overMinutes) {
            return response('Missing parameters', 400);
        }

        $audio = $this->elevenLabs->generateOverbreakAlert($agentName, (int) $overMinutes);

        if ($audio === null) {
            return response('Audio generation failed', 503);
        }

        return response($audio, 200)
            ->header('Content-Type', 'audio/mpeg')
            ->header('Content-Disposition', 'inline');
    }

    public function batchAlert(Request $request): Response
    {
        if (!$this->elevenLabs->isConfigured()) {
            return response('Voice alerts not configured', 503);
        }

        $agents = $request->input('agents', []);

        if (empty($agents)) {
            return response('No agents', 400);
        }

        $audio = $this->elevenLabs->generateOverbreakBatchAlert($agents);

        if ($audio === null) {
            return response('Audio generation failed', 503);
        }

        return response($audio, 200)
            ->header('Content-Type', 'audio/mpeg')
            ->header('Content-Disposition', 'inline');
    }

    /**
     * Get pending audio alerts (auto-generated by scheduled command)
     */
    public function getPendingAlerts(): Response
    {
        $cacheKey = 'pending_audio_alerts';
        $alerts = Cache::get($cacheKey);

        if (empty($alerts)) {
            return response()->json(['alerts' => [], 'count' => 0]);
        }

        return response()->json([
            'alerts' => $alerts,
            'count' => count($alerts),
        ]);
    }

    /**
     * Get next audio alert to play
     */
    public function getNextAlert(): Response
    {
        $cacheKey = 'pending_audio_alerts';
        $alerts = Cache::get($cacheKey);

        if (empty($alerts)) {
            return response('No pending alerts', 404);
        }

        $nextAlert = array_shift($alerts);

        // Update cache with remaining alerts
        if (!empty($alerts)) {
            Cache::put($cacheKey, $alerts, 300);
        } else {
            Cache::forget($cacheKey);
        }

        return response($nextAlert['audio'], 200)
            ->header('Content-Type', 'audio/mpeg')
            ->header('X-Alert-Agent', $nextAlert['agent_name'])
            ->header('X-Alert-Warning', $nextAlert['warning_number']);
    }

    /**
     * Clear all pending alerts
     */
    public function clearAlerts(): Response
    {
        Cache::forget('pending_audio_alerts');
        return response()->json(['success' => true, 'message' => 'All pending alerts cleared']);
    }

    /**
     * Test endpoint - generates a generic voice alert without requiring parameters.
     * Use this to test ElevenLabs integration.
     */
    public function testAlert(): Response
    {
        if (!$this->elevenLabs->isConfigured()) {
            return response('Voice alerts not configured. Set ELEVENLABS_API_KEY and ELEVENLABS_VOICE_ID in environment.', 503);
        }

        $audio = $this->elevenLabs->generateSpeech(
            "This is an overbreak notification. Agent Maria Santos has exceeded the allowable break duration by 20 minutes. Kindly address this matter promptly."
        );

        if ($audio === null) {
            return response('Audio generation failed', 503);
        }

        return response($audio, 200)
            ->header('Content-Type', 'audio/mpeg')
            ->header('Content-Disposition', 'inline');
    }

    /**
     * Test Slack notification
     */
    public function testSlack(): Response
    {
        if (!$this->slack->isConfigured()) {
            return response()->json(['success' => false, 'message' => 'Slack not configured. Set SLACK_WEBHOOK_URL in environment.'], 503);
        }

        $result = $this->slack->sendTestNotification();

        if ($result) {
            return response()->json(['success' => true, 'message' => 'Slack notification sent successfully.']);
        }

        return response()->json(['success' => false, 'message' => 'Failed to send Slack notification.'], 500);
    }
}
