<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3EHv3e3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3EHv3e3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3EHv3e3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3EHv3e3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3EHv3e3\App_KernelDevDebugContainer([
    'container.build_hash' => '3EHv3e3',
    'container.build_id' => '7a9c51de',
    'container.build_time' => 1774646276,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container3EHv3e3');
